@startuml

abstract class AbstractENBException
abstract class InvalidMoveException
class InvalidPawnMoveException
class InvalidKnightMoveException
class InvalidBishopMoveException
class InvalidRookMoveException
class InvalidQueenMoveException
class InvalidKingMoveException

class InvalidSquareException


@enduml