@startuml

class Board
class Game
class Player
class Square
enum Color
enum File
enum Piece

class Square {
    getFile() : File
    getRank() : int
}

class Board {
    getSize() : int
    getPiece(square : Square) : Piece
    getTurn() : Color
    setPiece(square : Square, piece : Piece) : void
    movePiece(placement : Square, destination : Square) : void
    switchTurn() : void
}

class Player {
    getName() : String
    getColor() : Color
}

enum Piece {
    getColor() : Color
}

class Game {
    getPlayers() : Player[]
    getBoard() : Board
}

enum File {
    getIndex() : int
}

@enduml