@startuml

class MoveController
class CurrentTurnController

class MoveController{
    movePiece(board: Board, placement : Square, destination : Square) : void
}

class CurrentTurnController {
    getCurrentTurn(board: Board)) : Color
}

@enduml